[package]
name = "major-pickems-sim"
description = "Simulate tournament stage outcomes for Counter-Strike major tournaments."
version = "0.1.0"
edition = "2024"
readme = "README.md"
license = "MIT"
homepage = "https://github.com/ndunnett/major-pickems-sim"
repository = "https://github.com/ndunnett/major-pickems-sim"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
itertools = "0.14.0"
rand = "0.9.1"
rayon = "1.10.0"
serde = "1.0.219"
serde_json = "1.0.140"

[[bin]]
name = "pickems"
path = "src/main.rs"

[profile.dev]
lto = "off"
opt-level = 0
panic = "abort"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"
strip = true
